"""initial migration

Revision ID: e16cdd4a9e58
Revises: 
Create Date: 2026-07-19 15:52:01.925298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16cdd4a9e58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # create schema
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS billing"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_pk', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('customer_pk'),
    sa.UniqueConstraint('email_id'),
    schema='billing'
    )
    op.create_table('product',
    sa.Column('product_pk', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('available_stocks', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('tax_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('product_pk'),
    sa.UniqueConstraint('product_id'),
    schema='billing'
    )
    op.create_table('bill',
    sa.Column('bill_pk', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_fk', sa.UUID(), nullable=False),
    sa.Column('total_price_without_tax', sa.Float(), nullable=False),
    sa.Column('total_tax_payable', sa.Float(), nullable=False),
    sa.Column('net_price_of_the_purchased_item', sa.Float(), nullable=False),
    sa.Column('rounded_down_value', sa.Float(), nullable=False),
    sa.Column('balance_payable_to_the_customer', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['customer_fk'], ['billing.customer.customer_pk'], ),
    sa.PrimaryKeyConstraint('bill_pk'),
    schema='billing'
    )
    op.create_table('bill_item',
    sa.Column('bill_item_pk', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bill_fk', sa.UUID(), nullable=False),
    sa.Column('product_fk', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchased_price', sa.Float(), nullable=False),
    sa.Column('tax_for_item', sa.Float(), nullable=False),
    sa.Column('tax_payable_for_items', sa.Float(), nullable=False),
    sa.Column('total_price_of_the_item', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['bill_fk'], ['billing.bill.bill_pk'], ),
    sa.ForeignKeyConstraint(['product_fk'], ['billing.product.product_pk'], ),
    sa.PrimaryKeyConstraint('bill_item_pk'),
    schema='billing'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_item', schema='billing')
    op.drop_table('bill', schema='billing')
    op.drop_table('product', schema='billing')
    op.drop_table('customer', schema='billing')
    # ### end Alembic commands ###
    op.execute(sa.text("DROP SCHEMA IF EXISTS billing CASCADE"))
