PRODUCTS = [
    {
        "product_id": 101,
        "product_name": "Laptop",
        "available_stocks": 20,
        "unit_price": 55000.00,
        "tax_percentage": 18.00,
    },
    {
        "product_id": 102,
        "product_name": "Keyboard",
        "available_stocks": 100,
        "unit_price": 850.00,
        "tax_percentage": 18.00,
    },
    {
        "product_id": 103,
        "product_name": "Mouse",
        "available_stocks": 150,
        "unit_price": 450.00,
        "tax_percentage": 18.00,
    },
    {
        "product_id": 104,
        "product_name": "Monitor",
        "available_stocks": 30,
        "unit_price": 12500.00,
        "tax_percentage": 18.00,
    },
    {
        "product_id": 105,
        "product_name": "USB Cable",
        "available_stocks": 200,
        "unit_price": 250.00,
        "tax_percentage": 12.00,
    },
    {
        "product_id": 106,
        "product_name": "Webcam",
        "available_stocks": 45,
        "unit_price": 2200.00,
        "tax_percentage": 18.00,
    },
    {
        "product_id": 107,
        "product_name": "Headphones",
        "available_stocks": 60,
        "unit_price": 3200.00,
        "tax_percentage": 18.00,
    },
    {
        "product_id": 108,
        "product_name": "Printer",
        "available_stocks": 15,
        "unit_price": 9800.00,
        "tax_percentage": 18.00,
    },
    {
        "product_id": 109,
        "product_name": "External Hard Drive",
        "available_stocks": 40,
        "unit_price": 5600.00,
        "tax_percentage": 18.00,
    },
    {
        "product_id": 110,
        "product_name": "Wireless Router",
        "available_stocks": 35,
        "unit_price": 3100.00,
        "tax_percentage": 18.00,
    },
]